#!/usr/bin/env bash
# $1: username
# $2: apikey

curl "https://identity.api.rackspacecloud.com/v2.0/tokens" \
  -d "{ \"auth\": { \"RAX-KSKEY:apiKeyCredentials\": { \"username\": \"$1\", \"apiKey\": \"$2\" } } }" \
  -H "Content-Type: application/json" 

